#############
### build ###
#############

# base image
FROM groupclaes/npm as build

# install chrome for protractor tests
# RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
# RUN apt-get update && apt-get install -yq google-chrome-stable
USER root

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
# ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
COPY .npmrc ./.npmrc

ENV NODE_ENV test
RUN npm install --ignore-scripts -g @angular/cli && npm install --ignore-scripts --legacy-peer-deps

#ENV NODE_ENV production

# add app
COPY ./src /app/src
# COPY server.ts /app/server.ts
COPY angular.json /app/angular.json
COPY tsconfig.json /app/tsconfig.json
COPY tsconfig.app.json /app/tsconfig.app.json
COPY tailwind.config.js /app/tailwind.config.js
COPY ngsw-config.json /app/ngsw-config.json

RUN ng build --configuration staging --output-path=dist --verbose 
# RUN ng build --configuration production --output-path=dist 
# RUN ng build --output-path=dist

############
### prod ###
############

# base image
FROM groupclaes/nginx:latest

#remove all content form html
RUN rm -rf /usr/share/nginx/html/*

# copy artifact build from the 'build environment'
COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

# expose port 80
EXPOSE 80
